In [2]:
user_name = input("Enter your name: ")

password = input("Enter your password: ")

if user_name== "Admin" and password == "Admin":
    print("You are Correct user ")
else:
    print("who are you")

Enter your name: Admin
Enter your password: Admin
You are Correct user

In [8]:
user_name = input("Enter your name: ")

password = input("Enter your password: ")

if user_name.lower()== 'admin' and password == 'Admin':
    print("You are Correct user ")
else:
    print("who are you")

Enter your name: Admin
Enter your password: Admin
You are Correct user

In [ ]:
data = [{'Name':"Muhammad Saad",'id': '79' ,'email':'saadibrahim@gmail.com','phone_number': '923312090998', 'pass' : '123'},
         {'Name':"muhammad zohair",'id': '81' ,'email':'muhammadzohair57@gmail.com','phone_number': '923323144843', 'pass' : '456'} , 
        {'Name':"Saifullah umrani",'id': '2299' ,'email':'saifumrani57@gmail.com','phone_number': 923362013118, 'pass' : '789'},
        {'Name':"Zaid umrani",'id': '8987' ,'email':'zaidumrani57@gmail.com','phone_number': '923331226065' , 'pass' : '123'},
        {'Name':"Ubaid Ahmed",'id': '3345' ,'email':'ubaidahmed09@gmail.com','phone_number': '923333122602' , 'pass' : '865'}]
user_name = input(" Enter your Name , phone-no , email , id :   ")
password = input("Enter your password : ")

for record in data:
    if record['Name'] == user_name or record['id'] == user_name or record['email'] == user_name or record['phone_number'] == user_name:
        if record['pass']== password:
            print("correct")
            break
else:
    print("not valid at all")

In [40]:
num = int(input("Enter a number: "))

for i in range(1 ,11):
    print(f"{num} x {i} = {num * i}")

Enter a number: 89
89 x 1 = 89
89 x 2 = 178
89 x 3 = 267
89 x 4 = 356
89 x 5 = 445
89 x 6 = 534
89 x 7 = 623
89 x 8 = 712
89 x 9 = 801
89 x 10 = 890

In [56]:
for i in range(1 ,11):
    print("\n")
    for j in range(1 , 11):
        print(f"{i} X {j} = {i * j}")

1 X 1 = 1
1 X 2 = 2
1 X 3 = 3
1 X 4 = 4
1 X 5 = 5
1 X 6 = 6
1 X 7 = 7
1 X 8 = 8
1 X 9 = 9
1 X 10 = 10


2 X 1 = 2
2 X 2 = 4
2 X 3 = 6
2 X 4 = 8
2 X 5 = 10
2 X 6 = 12
2 X 7 = 14
2 X 8 = 16
2 X 9 = 18
2 X 10 = 20


3 X 1 = 3
3 X 2 = 6
3 X 3 = 9
3 X 4 = 12
3 X 5 = 15
3 X 6 = 18
3 X 7 = 21
3 X 8 = 24
3 X 9 = 27
3 X 10 = 30


4 X 1 = 4
4 X 2 = 8
4 X 3 = 12
4 X 4 = 16
4 X 5 = 20
4 X 6 = 24
4 X 7 = 28
4 X 8 = 32
4 X 9 = 36
4 X 10 = 40


5 X 1 = 5
5 X 2 = 10
5 X 3 = 15
5 X 4 = 20
5 X 5 = 25
5 X 6 = 30
5 X 7 = 35
5 X 8 = 40
5 X 9 = 45
5 X 10 = 50


6 X 1 = 6
6 X 2 = 12
6 X 3 = 18
6 X 4 = 24
6 X 5 = 30
6 X 6 = 36
6 X 7 = 42
6 X 8 = 48
6 X 9 = 54
6 X 10 = 60


7 X 1 = 7
7 X 2 = 14
7 X 3 = 21
7 X 4 = 28
7 X 5 = 35
7 X 6 = 42
7 X 7 = 49
7 X 8 = 56
7 X 9 = 63
7 X 10 = 70


8 X 1 = 8
8 X 2 = 16
8 X 3 = 24
8 X 4 = 32
8 X 5 = 40
8 X 6 = 48
8 X 7 = 56
8 X 8 = 64
8 X 9 = 72
8 X 10 = 80


9 X 1 = 9
9 X 2 = 18
9 X 3 = 27
9 X 4 = 36
9 X 5 = 45
9 X 6 = 54
9 X 7 = 63
9 X 8 = 72
9 X 9 = 81
9 X 10 = 90


10 X 1 = 10
10 X 2 = 20
10 X 3 = 30
10 X 4 = 40
10 X 5 = 50
10 X 6 = 60
10 X 7 = 70
10 X 8 = 80
10 X 9 = 90
10 X 10 = 100

In [61]:
n = int(input("Enter a number"))
m = int(input("Enter a number"))

for i in range(1 , n+1):
    print(f"Multiplication of {i} is :" )
    for j in range(1 , m+1):
        print(f"{i} X {j} = {i * j}")

Enter a number6
Enter a number7
Multiplication of 1 is :
1 X 1 = 1
1 X 2 = 2
1 X 3 = 3
1 X 4 = 4
1 X 5 = 5
1 X 6 = 6
1 X 7 = 7
Multiplication of 2 is :
2 X 1 = 2
2 X 2 = 4
2 X 3 = 6
2 X 4 = 8
2 X 5 = 10
2 X 6 = 12
2 X 7 = 14
Multiplication of 3 is :
3 X 1 = 3
3 X 2 = 6
3 X 3 = 9
3 X 4 = 12
3 X 5 = 15
3 X 6 = 18
3 X 7 = 21
Multiplication of 4 is :
4 X 1 = 4
4 X 2 = 8
4 X 3 = 12
4 X 4 = 16
4 X 5 = 20
4 X 6 = 24
4 X 7 = 28
Multiplication of 5 is :
5 X 1 = 5
5 X 2 = 10
5 X 3 = 15
5 X 4 = 20
5 X 5 = 25
5 X 6 = 30
5 X 7 = 35
Multiplication of 6 is :
6 X 1 = 6
6 X 2 = 12
6 X 3 = 18
6 X 4 = 24
6 X 5 = 30
6 X 6 = 36
6 X 7 = 42

In [66]:
data = [{'Name':"Muhammad Saad",'id': '79' ,'email':'saadibrahim@gmail.com','phone_number': '923312090998', 'pass' : '123'},
         {'Name':"muhammad zohair",'id': '81' ,'email':'muhammadzohair57@gmail.com','phone_number': '923323144843', 'pass' : '456'} , 
        {'Name':"Saifullah umrani",'id': '2299' ,'email':'saifumrani57@gmail.com','phone_number': 923362013118, 'pass' : '789'},
        {'Name':"Zaid umrani",'id': '8987' ,'email':'zaidumrani57@gmail.com','phone_number': '923331226065' , 'pass' : '123'},
        {'Name':"Ubaid Ahmed",'id': '3345' ,'email':'ubaidahmed09@gmail.com','phone_number': '923333122602' , 'pass' : '865'}]

for record in data:
    Card = """
    NAME = {Name}
    ID = {id}
    Email = {email}
    Phone Number = {phone_number} 
     """.format_map(record)
    print(Card)

    NAME = Muhammad Saad
    ID = 79
    Email = saadibrahim@gmail.com
    Phone Number = 923312090998


    NAME = muhammad zohair
    ID = 81
    Email = muhammadzohair57@gmail.com
    Phone Number = 923323144843


    NAME = Saifullah umrani
    ID = 2299
    Email = saifumrani57@gmail.com
    Phone Number = 923362013118


    NAME = Zaid umrani
    ID = 8987
    Email = zaidumrani57@gmail.com
    Phone Number = 923331226065


    NAME = Ubaid Ahmed
    ID = 3345
    Email = ubaidahmed09@gmail.com
    Phone Number = 923333122602

In [71]:
dir(str)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']

In [73]:
counter = 67

while counter > 34:
    print(counter)
    counter -= 3

67
64
61
58
55
52
49
46
43
40
37